language: scala
sudo: false
scala:
- 2.12.11
- 2.13.3
dist: xenial
jdk: openjdk8
matrix:
  include:
  - jdk: openjdk11
    scala: 2.12.11
script:
- sbt "scalafmtCheck" "test:scalafmtCheck" "scalafmtSbtCheck" "++ ${TRAVIS_SCALA_VERSION}! -v" test
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
